### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by xiaojidan** [iro-cp/FCRN-DepthPrediction#1]
Can you share the training codes for training our own datasets? We want to evaluate your method on the complex datasets?

**Comment by iro-cp** [comment]
Hi, 
I plan to share code for training as well in the (near) future. However, please keep in mind that for training on your own dataset some modifications would probably have to be applied anyway.

**Comment by xiaojidan** [comment]
OK. @iro-cp  Thanks a lot. I am keeping in mind for your project. Good Luck~

**Comment by iro-cp** [comment]
Thanks!
