### ISSUE TITLE
Error when running your TensorFlow code-predict.py

### ISSUE THREAD

**Issue by chenynCV** [iro-cp/FCRN-DepthPrediction#12]
line 46, in setup .conv(1, 1, 512, 2, 2, biased=False, relu=False, name='res3a_branch1')
ValueError: ('stride must be less than or equal to filter size', 'stride: [2x2] filter: [1x1]')

**Comment by chenynCV** [comment]
Refer to [this issue](https://github.com/tensorflow/tensorflow/issues/889)) for detail.

You can try [this](https://github.com/ry/tensorflow/commit/afa816200ec3bf415519b0d8173b2fcc7d0679e0) .

**Comment by chrirupp** [comment]
This is strange, as it working fine for us. Which version of TF are you using?

**Comment by chenynCV** [comment]
v0.8

**Comment by chrirupp** [comment]
We are using 0.12 so that might be the cause. Can you upgrade your TF?

**Comment by chenynCV** [comment]
OK. I will try.

**Comment by chenynCV** [comment]
I fix it by upgrade TensorFlow to v1,0. Thank you for your adverse.
