### ISSUE TITLE
Question about  train code of matconvnet

### ISSUE THREAD

**Issue by rainy1798** [iro-cp/FCRN-DepthPrediction#15]
Hello，
I have a problem，I don't know how to use your methods to train。
Can you give me the original training code of matconvnet? I want to know more details about your experiment。So if you are willing，Please share your training source code of matconnet give me。thanks

**Comment by iro-cp** [comment]
Hi, 
We might release the training code in the future. 
For details regarding experiments and training, you could have a look at the paper :)
