### ISSUE TITLE
Make3D Preprocessing

### ISSUE THREAD

**Issue by srv902** [iro-cp/FCRN-DepthPrediction#18]
Hi there,

Is there any preprocessing that needs to be done for Make3D training samples apart from the part that depths below 70m only are considered?

 Thank You.

**Comment by iro-cp** [comment]
Hey, 
for more details on Make3D pre-processing, please have a look at our paper, section 4.3 
Briefly, we resize all images & corresponding ground truth depth maps to the same resolution, apply small augmentations (detailed in https://www.cs.nyu.edu/~deigen/depth/depth_nips14.pdf, section 3.4) and mask out invalid pixels and those > 70m.

**Comment by chrirupp** [comment]
closing this since it has been open for a while. Feel free to reopen if you have further questions.

**Comment by ExonRen** [comment]
@iro-cp So you mean you simply do data augmentation like Sec3.4 in Eigen2014 to make Make3D from 500 images to 15k?
