### ISSUE TITLE
Matlab version

### ISSUE THREAD

**Issue by CatherineYao** [iro-cp/FCRN-DepthPrediction#20]
Hi, I found websave function is not exist in my matlab R2014a.  So it will result in error when websave is used  in .m file. What can I do to solve this problem？

**Comment by vinthony** [comment]
hi, Maybe you could download the link directly from the web according to URL in [#line72](https://github.com/iro-cp/FCRN-DepthPrediction/blob/master/matlab/evaluateNYU.m#L72) and [#line80](https://github.com/iro-cp/FCRN-DepthPrediction/blob/master/matlab/evaluateNYU.m#L80)

**Comment by iro-cp** [comment]
As @vinthony  suggests, you can copy the URLs or alternatively try replacing websave with urlwrite for older matlab versions.

**Comment by CatherineYao** [comment]
I've tried use urlwrite, but the content of two .mat files is "<html><frameset> <frame id='top' src="http://10.100.40.254/disable/disable.htm"><noframes> <body>Your browse does not support frame!</body> </noframes> </frameset> </html>" .

**Comment by CatherineYao** [comment]
Thank you very much. Maybe I should download the link directly with url. @vinthony @iro-cp

**Comment by CatherineYao** [comment]
I've used Internet Download Manager to download the mat files, but it still occurred the problem "Your browse does not support frame! ". Is it relevant to file transfer protocol？

**Comment by vinthony** [comment]
I am not sure what cause this problem, Maybe you could try to change a browser.

Chrome is a good choice for you to download the URL.

Just paste the URL into the address bar of the browser and enter 'Return'

Or

you could download the URL from their website.

for the labelled data:

> http://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html

for the split data:

> http://cs.nyu.edu/~silberman/projects/indoor_scene_seg_sup.html
