### ISSUE TITLE
Hey.On which machine did you train the model?.I am trying run this pretrained model of yours on Titan X GPU machine with 16 GB ram.But my machine reboots.which seems due to excessive load on the machine!

### ISSUE THREAD

**Issue by shivamakhauri04** [iro-cp/FCRN-DepthPrediction#21]

**Comment by chrirupp** [comment]
Hi shivamakhauri04,

we are running the model on various different machines including laptops without problems. Usually a system reboot due to GPU load indicates a hardware problem with the machine. There is nothing in our code that forces a restart of the system.

Best,
Christian

**Comment by shivamakhauri04** [comment]
Thank you so much..Will try finding the issue.
CAN/WILL YOU RELEASE THE TRAINING DATA AND THE TRAINING CODE

**Comment by shivamakhauri04** [comment]
If you release the training code and data ,it would be very good understanding for me.the paper explains the concepts,but implementation part ,I m struggling

**Comment by shivamakhauri04** [comment]
Please respond.....Training code for **tensorflow**....Will be highly obliged

**Comment by bazilas** [comment]
you could study the matconvnet model. it essentially describes the paper. for the training details, you may refer to the paper.
