### ISSUE TITLE
Reduce computational time

### ISSUE THREAD

**Issue by prachi92sharma** [iro-cp/FCRN-DepthPrediction#28]
It is taking more than a minute to calculate depth map, How can i reduce this time?

**Comment by iro-cp** [comment]
Are you referring to the inference for a single image? Do you maybe include the time for loading the weights?
Also, are you using a CPU or GPU? Using a Titan X GPU, it should take approximately 50ms for a single image.

**Comment by hav4ik** [comment]
On CPU (Core i7) it took me approx. 1 second for one forward pass. It shouldn't be much slower on other laptop or desktop CPUs. Perhaps you are taking into account the loading time (for me it is ~40 sec).

Take a closer look at the code and do the network loading separatedly.
