### ISSUE TITLE
Question about test the image

### ISSUE THREAD

**Issue by Kn15263ss** [iro-cp/FCRN-DepthPrediction#30]
Hello, I have a little problem, I try to test the image on preduct,py.
When I input commend "python predict.py NYU_ResNet-UpProj.npy (my own image)", it's get a error like this:
![image](https://user-images.githubusercontent.com/22387638/31940986-b97f113a-b8f2-11e7-919f-d38c92c84269.png)

How to fix it problem?
Thanks you!!

**Comment by sjwhhhi** [comment]
I have the same question.
Maybe the code should be fixed.

**Comment by chrirupp** [comment]
Hi guys,

You should probably load the checkpoint file instead of the npy.

Let me know if that helps!
Christian

**Comment by Kn15263ss** [comment]
Yes, I have also load the checkpoint file, it's still same problem.

**Comment by chrirupp** [comment]
What version of tensorflow are you using?

**Comment by Kn15263ss** [comment]
I use 1.3.0 version.

**Comment by chrirupp** [comment]
This is strange, it is working for us fine. What is the error that you get with the checkpoint?

**Comment by Kn15263ss** [comment]
![image](https://user-images.githubusercontent.com/22387638/32037664-e39c289c-ba58-11e7-824a-0c1ef421e7b2.png)
![image](https://user-images.githubusercontent.com/22387638/32037677-f5756b78-ba58-11e7-9d62-e779559ed65d.png)

Do I need change the name of NYU_FCRN.ckpt.xxx file??

**Comment by TUSSON** [comment]
Please try ```python predict.py NYU_FCRN.ckpt 1.JPG```

**Comment by Kn15263ss** [comment]
It's can working!   Thanks you!! @TUSSON  and @chrirupp
