### ISSUE TITLE
Question about show the prediction

### ISSUE THREAD

**Issue by sjwhhhi** [iro-cp/FCRN-DepthPrediction#33]
I used opencv to do the prediction in  real-time by Opencv. However, I got the output only in black and white, without any color. Which type of data" is pred[0,:,:,0]" ? How should I do with opencv?
Could you help me?
Thank U very much.

**Comment by iro-cp** [comment]
The prediction is a depth map, so there aren't supposed to be any colors. You need to apply a colormap, e.g. jet (same one we used for our images). OpenCV supports that too.
