### ISSUE TITLE
About test images which used by your paper?

### ISSUE THREAD

**Issue by JackHenry1992** [iro-cp/FCRN-DepthPrediction#36]
Hi, @iro-cp , I can't find the test images in nyu official website.
**Can you provide origin test_images used by your paper?**
As I think that only use the same test_images can validation inference. And it's important to unify the same standard.

**Comment by chrirupp** [comment]
as we say in the paper, it is the validationset of NYU-depth v2 (https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html)
