### ISSUE TITLE
Padding side might be wrong

### ISSUE THREAD

**Issue by ieted** [iro-cp/FCRN-DepthPrediction#40]
Hi,

I was trying to reimplement your awesome work using PyTorch this afternoon but met a trouble on your fast up-projection implementation.

In your `unpool_as_conv` function, convB/C/D was computed after an asymmetric padding. However, after I decompose the up-pooling and 5x5 conv computation to the interleaved sum of four smaller convolution results by hands, I found that paddings bebore convB/C/D should be `[[0, 0], [0, 1], [1, 1], [0, 0]], [[0, 0], [1, 1], [0, 1], [0, 0]] and [[0, 0], [0, 1], [0, 1], [0, 0]]` instead of `[[0, 0], [1, 0], [1, 1], [0, 0]], [[0, 0], [1, 1], [1, 0], [0, 0]] and [[0, 0], [1, 0], [1, 0], [0, 0]]`. So is it possible that padding side in the code was wrongly set by mistake?

**Comment by irolaina** [comment]
Hello, 

that's a good observation and you are perfectly right. Actually we directly trained the NYU model with the interleaved convolutions, in which case the order of the asymmetric padding does not matter. There we set it arbitrarily, to be honest. 

However, when converting the model from the slower 5x5 version to the faster one, the padded side matters to get equivalent results. Our Make3D model was only trained in the 5x5 conv setup and consecutively converted using the correct padding (as you point out too). 

Thanks for your comment!

**Comment by ieted** [comment]
Thanks for the clarification. 

Cheers.
