### ISSUE TITLE
Have you set the weight decay during the traning?

### ISSUE THREAD

**Issue by luohongcheng** [iro-cp/FCRN-DepthPrediction#43]
Hi~ Laina, I want to ask, Have you set the weight decay  of the convolution layers？

**Comment by irolaina** [comment]
Hi, weight decay is set to 0.0005 for all layers.

**Comment by Ariel-JUAN** [comment]
@iro-cp Hi, weight decay is set to 0.0005 for all layers.  Do you mean all trainable variables use weight decay including BN layer?
