### ISSUE TITLE
is this a bug? can't run normally when use matlab, error in net.eval(inputs);

### ISSUE THREAD

**Issue by peter2013wkl** [iro-cp/FCRN-DepthPrediction#44]
test the matlab version, use the  NVU_ResnNet-UpProj.mat (download from the project github)when load a RGB image,  when run to prediction..., and net.eval(inputs) ;  return error:
==================================
Error in dagnn.Conv/forward (line 11)
       output{1} = vl_nnconv(...
Error in dagnn.Layer/forwardAdvanced (line 85)
        outputs = obj.forward(inputs, {net.params(par).value}) ;
Error in dagnn.DagNN/eval (line 88)
        obj.layers(l).block.forwardAdvanced(obj.layers(l)) ;
Error in DepthMapPrediction (line 65)
        net.eval(inputs);

fx>>

=======================

what is the problem?  please help, thanks a lot!

**Comment by chrirupp** [comment]
Hi peter2013wkl,
please post the full error message.

**Comment by chrirupp** [comment]
closing after inactivity for a month
