### ISSUE TITLE
Why the colormap performs incorrectly by opencv

### ISSUE THREAD

**Issue by sjwhhhi** [iro-cp/FCRN-DepthPrediction#46]
![1515496941 1](https://user-images.githubusercontent.com/28922123/34718664-ec388038-f57a-11e7-8c51-671b15f96e53.png)
By matplotlib, it is good.
However, it becomes like this by opencv.
![1515496966 1](https://user-images.githubusercontent.com/28922123/34718689-ff284d4a-f57a-11e7-9bec-5bb859e20861.png)
Can anyone tell me? Thanks

**Comment by Ariel-JUAN** [comment]
I also encounter this problem, do you know how to solve it? The image can only be saved with uint8, and the test image is strange.

**Comment by sjwhhhi** [comment]
@Ariel-JUAN 
I have solved the problem. You should normalize the result.

**Comment by Nilay27** [comment]
how did you convert the image using opencv?
