### ISSUE TITLE
Why the lr-0.01 is too large for me?

### ISSUE THREAD

**Issue by Ariel-JUAN** [iro-cp/FCRN-DepthPrediction#47]
When I set the lr as 0.01, I think the network learn nothing,  the images in tensorboard are just all black. Besides, sometimes, the initial loss will become so large or nan. I use the raw NYU images, and the images are about 95k, can you give me some advice?
@iro-cp

**Comment by chrirupp** [comment]
Hi, are you dividing each image by the number of valid pixels?

**Comment by Ariel-JUAN** [comment]
Yes, when I compute loss, the image is divided by the number of valid pixels.

**Comment by ieted** [comment]
Hi @Ariel-JUAN , I'm also suffering a gradient explosion problem(loss become nan within 10 iterations). Have you figured out where the problem might be?
