### ISSUE TITLE
sth wrong

### ISSUE THREAD

**Issue by taotaoland** [iro-cp/FCRN-DepthPrediction#5]
>>evaluateNYU()
loading data to workspace... done!
predicting...
Error using vl_nnconv
An input is not a numeric array (or GPU support not compiled).

Error in dagnn.Conv/forward (line 11)
      outputs{1} = vl_nnconv(...

Error in dagnn.Layer/forwardAdvanced (line 85)
      outputs = obj.forward(inputs, {net.params(par).value}) ;

Error in dagnn.DagNN/eval (line 88)
  obj.layers(l).block.forwardAdvanced(obj.layers(l)) ;

Error in DepthMapPrediction (line 60)
    net.eval(inputs) ;

Error in evaluateNYU (line 47)
predictions = DepthMapPrediction(testSet, net, netOpts);

**Comment by iro-cp** [comment]
It seems like you might have an issue with GPU support, in which case I would suggest you to look into their documentation or maybe this thread helps: 
https://github.com/vlfeat/matconvnet/issues/99
