### ISSUE TITLE
I want to knwo can this model estimate the real distance?

### ISSUE THREAD

**Issue by sjwhhhi** [iro-cp/FCRN-DepthPrediction#51]
Can I estimate the real distance after prediction? Can I get like some depth information besides color?
Thank U!

**Comment by irolaina** [comment]
The colors simply come from a colormap for plotting. The actual pixel values of the prediction represent real distances, specifically in meters.

**Comment by sjwhhhi** [comment]
@iro-cp 
Thank for replyling!
You mean distance is available? But how can I get the pixel values of prediction?
Thank U!

**Comment by oneTimePad** [comment]
@iro-cp  Is there a correction factor necessary when a different camera is used, not Xbox Kinect? This was mentioned in the paper on CNN-SLAM. Do you know the focal length of the Kinect used for the training dataset?

**Comment by chrirupp** [comment]
@sjwhhhi you run our code an access the output. 

@oneTimePad you are correct. The focal length can be found in the NYU-Depth dataset camera calibration files. Here: https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html
