### ISSUE TITLE
Where can I find train/test split for NYUD v2 unlabeled data?

### ISSUE THREAD

**Issue by ghost** [iro-cp/FCRN-DepthPrediction#53]
I downloaded the unlabeled dataset separately and can't find train/test split information anywhere.

**Comment by irolaina** [comment]
Hi, the train/test split can be downloaded using our code. You can also download the file here:
http://horatio.cs.nyu.edu/mit/silberman/indoor_seg_sup/splits.mat

**Comment by ghost** [comment]
@iro-cp Thanks a lot.
