### ISSUE TITLE
Make3d augmentation code

### ISSUE THREAD

**Issue by buaaswf** [iro-cp/FCRN-DepthPrediction#56]
Could you share the pre-processing code to the make3d dataset? I can not find how to augment the training dataset from 343 to 15k， thank you

**Comment by AI-slam** [comment]
I also need the pre-processing code too, thanks!@buaaswf

**Comment by irolaina** [comment]
Hi, it is the standard process of random transformations, i.e. rotations, scaling, cropping, mirroring and color transformations. You can have a look at [this repository](https://github.com/aleju/imgaug) for a wide range of image augmentations for deep learning.
