### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by lemianli** [iro-cp/FCRN-DepthPrediction#6]
Hello,I'm a maching learning new learner.I have read your acticle,it's pretty nice;I've learned a lot from your paper and run the code successfully and get the final results.However,I have some questions.
The core concept in your paper is your proposed CNN Architecture,right? In Experimental,Your article evaluate the influence of the depth of the architecture using the convolutional blocks of AlexNet,VGG-16 and ResNet-50,I try to replace your  NYU_ResNet-UpProj.mat with imagenet-resnet-50-dag.mat directly,it makes errors.Later I know that the architecture of Resnet-50 need to be changed, May replacing the last full conections with fully convolutional?
Sincerely expected your reply.Thanks a lot.

**Comment by iro-cp** [comment]
Hi, 

The ResNet-50 architecture is slightly modified, only the last layers have to be removed (i.e. average pooling, fully-connected layer and softmax loss), before plugging in the upsampling part.

`net = load(imagenet-resnet-50-dag.mat');`
net = dagnn.DagNN.loadobj(net) ;
net.removeLayer('pool5');   %last pooling
net.removeLayer('prob');    %softmax
net.removeLayer('fc1000');  %fully-connected layer`

But please note that the architecture in NYU_ResNet-UpProj.mat already includes these changes.
Similarly for AlexNet or VGG-16 one would have to remove all fully connected layers.
