### ISSUE TITLE
NYU Depth v2 Preprocessing

### ISSUE THREAD

**Issue by nicolasrosa** [iro-cp/FCRN-DepthPrediction#64]
Did you train the model on the Kinect's raw depth images (uint16) OR Did you implement the following calculations in your preprocessing routine? Did you also swap the bytes from the depth image?

**imgDepthOrig:** swapbytes(kinect_raw_depth_image_uint16)
**imgDepthAbs:** Absolute depth in meters*

*I believe this will be between 0~10m. Is that correct?

**Code:**
depthParam1 = 351.3;
depthParam2 = 1092.5;
imgDepthAbs = depthParam1 ./ (depthParam2 - imgDepthOrig);

**Matlab Script from dataset's toolkit:**
[depth_rel2depth_abs.txt](https://github.com/iro-cp/FCRN-DepthPrediction/files/1993158/depth_rel2depth_abs.txt)

**Comment by Ariel-JUAN** [comment]
Yes, it is between 0~10m.
