### ISSUE TITLE
Difference between two pre-trained models

### ISSUE THREAD

**Issue by crazylyf** [iro-cp/FCRN-DepthPrediction#8]
Hi, all. There are an in-door and an out-door pre-trained model, are there much differences between them? I want to estimate the depth for some images containing both in-door and out-door images, which one should I use, and Does that matter?

**Comment by iro-cp** [comment]
Hi, 
the models have both the same architecture, but they are trained separately on different datasets. 
The model for indoors is trained on NYU Depth v2, where scenes are in a range 0-10m, and the one for outdoors on Make3D, that is 0-70m. 
You can choose accordingly for your problem, however inaccuracies might occur in terms of global scale if the distances in your images are very different to what the models had been trained with.
