### ISSUE TITLE
Why loss the link of .ckpt file ?

### ISSUE THREAD

**Issue by ChenMathilda** [iro-cp/FCRN-DepthPrediction#97]
Hi,
I try to use this net to do a prediction but I cann't find the .ckpt file.
I noticed that your .ckpt had a link before, why do you delete its link now?
Because I just want to know the prediction effect of the low-precision picture as input for depth estimation, I wonder if you can provide a .ckpt file or  its link?
Regard，
Mathilda.

**Comment by KhuongDiep911** [comment]
Hi, 

I see that you close the issue, did you find the link to download the model checkpoint?
Can you tell me how to download it?

Thank you in advance,
Khuong

**Comment by wayne931121** [comment]
Hello I can tell you how to find trained model. First see the link in github is http://campar.in.tum.de/files/rupprecht/depthpred/NYU_FCRN-checkpoint.zip

Second Search NYU_FCRN-checkpoint.zip in google, and then you will find some result like https://storage.openvinotoolkit.org/repositories/open_model_zoo/public/2022.1/fcrn-dp-nyu-depth-v2-tf/?sort_by=BIG2SMALL
